### ISSUE TITLE
Support Packaging and Import of Proto files

### ISSUE THREAD

**Issue by nattyddubbs** [thesamet/sbt-protoc#1]
In sbt-proto you can both package and import proto files from other JAR files using the PB.protobuf config command as outlined [here](https://github.com/sbt/sbt-protobuf/#packaging-proto-files). I would like to still be able to do this with this library. Is there a analogous functionality that currently exists for this?

**Comment by thesamet** [comment]
Yes, just add the dependency to the `"protobuf"` configuration in your build.sbt. For example:
 
```
libraryDependencies += "x.y" % "z" % "1.0" % "protobuf"
```

**Comment by nattyddubbs** [comment]
Does this also work for the export process?

unmanagedResourceDirectories in Compile += (sourceDirectory in PB.protobufConfig).value

Will this put the *.proto files in the exported JAR?

**Comment by thesamet** [comment]
The equivalent will be

```
unmanagedResourceDirectories in Compile ++= (PB.protoSources in Compile).value
```

**Comment by nattyddubbs** [comment]
Okay I see. Thank you for the assistance.
