### ISSUE TITLE
sbt plugins customizing PB.targets cannot play nice together in Test

### ISSUE THREAD

**Issue by bjaglin** [thesamet/sbt-protoc#108]
In one project, we are using several plugins that `AutoPlugin#require` `ProtocPlugin` to customize `PB.targets` ([akka-grpc](https://github.com/akka/akka-grpc/blob/0a53ed/sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala#L97-L98) & other custom plugins).

`AkkaGrpcPlugin` (up to 0.7.1) turned out to **set** `PB.targets`, making it impossible to make it play well with another plugins without introducing an explicit `require` dependency between plugins, as detailed in https://github.com/akka/akka-grpc/pull/696.

Unfortunately, moving from **set** to **append** to customize `PB.targets` means that targets from parent configurations end up sticking around because of https://github.com/thesamet/sbt-protoc/blob/09c8eeb/src/main/scala/sbtprotoc/ProtocPlugin.scala#L145, which in most situation isnot wanted, as:
* `PB.targets` include configuration-specific output paths, that we don't want to rerun downstream
* `protoc-bridge` does not handle the repetition of a given `JvmGenerator` within the same run - `protoc` simply hangs, probably because of a race in the FIFOs, although I did not investigate

I have opened https://github.com/akka/akka-grpc/pull/702 to work-around this in `AkkaGrpcPlugin`, but it's hacky at best, so I am wondering if we could consider reverting https://github.com/thesamet/sbt-protoc/pull/16? That would obviously be a breaking change for clients invoking `protobufConfigSettings` "late" on children configuration (those with a parent), but it turns out this convenience comes at the cost of less interoperability for other plugins.

For `PB.protocOptions`, `PB.protoSources` & `PB.includePaths` that #16 also touched, one can argue that inheriting values for these keys makes sense since they do not define target/output paths.

**Comment by bjaglin** [comment]
cc @xuwei-k since I am challenging your PR

**Comment by thesamet** [comment]
I'm ok with reverting #16 - though I will appreciate @xuwei-k 's input.

**Comment by bjaglin** [comment]
any objection @xuwei-k ?
