### ISSUE TITLE
Change output location

### ISSUE THREAD

**Issue by nvartolomei** [thesamet/sbt-protoc#11]
Can output location be changed form `target/. . ./src_managed` to `src`?

**Comment by BryceCicada** [comment]
Try with ```scalaSource``` from sbt, like:
```scala
PB.targets in Compile := Seq(
  scalapb.gen() -> (scalaSource in Compile).value
)
```

**Comment by nvartolomei** [comment]
@BryceCicada almost, it just deleted scalaSource folder. :)

**Comment by BryceCicada** [comment]
Ah, I see.  I tried this out on a project used exclusively for compiling .proto files, on which other projects depend.  That is, I had no code in ```scalaSource``` so I hadn't noticed this behaviour.

You could try with:
```scala
PB.deleteTargetDirectory := false
```
but then you'd have to do the housekeeping of generated code yourself.

**Comment by nvartolomei** [comment]
We are getting closer. Last problem, now compile errors out with duplicate class definitions., because sbt-protoc messes with `libraryDependencies`.

**Comment by BryceCicada** [comment]
Sad times.  I'm not much more help I'm afraid... I've only been a user of this library for a few hours.

On a side note; I guess you have reasons for putting generated code into your ```src``` folder, but I imagine this is not a well-trodden path.  For example, one might typically have own code under version control but not generated code, and then have a build (under version control) that creates the generated code.  I guess that's what ```target/src_managed``` is for, if you exclude ```target``` from version control.

**Comment by nvartolomei** [comment]
@BryceCicada in my case I need to have all code under source control, including generated one.

**Comment by thesamet** [comment]
Maybe a subdirectory of src/main then?

```PB.targets in Compile := Seq(
  scalapb.gen() -> baseDirectory.value / "src/main/scala-protos")
```

**Comment by nvartolomei** [comment]
@thesamet hm, this solution is good enough. Thanks.
