### ISSUE TITLE
Refer generated class files in sub projects

### ISSUE THREAD

**Issue by sidtandon2014** [thesamet/sbt-protoc#137]
Hi,

I am able to generate scala files from proto message, and able to execute the flow end to end. This is working fine if there is one main project, but I am unable to refer these generated files from subprojects. How can I do that?

**Comment by thesamet** [comment]
@sidtandon2014 , a standard `dependsOn` in build.sbt should be sufficient for one sub-project to be able to access the generated classes of another subproject. There is an example here: https://github.com/thesamet/sbt-protoc/blob/a2e86f770b5273dbcfb1f0ce81a405b1d169503e/examples/multi-with-external-jar/build.sbt#L45

If you have tried this already, maybe you can share a minimal example of what you're trying to do and we can take a look.

**Comment by sidtandon2014** [comment]
Not sure if I am doing it correctly. Below is project structure

![image](https://user-images.githubusercontent.com/6470596/73969862-283d5a00-4942-11ea-8662-ad54b6d06d49.png)


and build.sbt code snippet. (Here common, ingress are dependent on protos and "dependencies.sparksqlScalapb" is "com.thesamet.scalapb" %% "sparksql-scalapb" % "0.9.0"

lazy val global = project
  .in(file("."))
  .settings(settings)
  .disablePlugins(AssemblyPlugin)
  .aggregate(
    protos,
    common,
    ingress,
    egress,
    cdrin,
    ingressTPS,
    egressTPS
  )

lazy val protos = project
  .settings(
    name := "resources",
    settings,
    libraryDependencies ++= Seq(dependencies.sparksqlScalapb),
    PB.protoSources in Compile += Seq(baseDirectory.value / "resources/protobuf"),

    PB.targets in Compile := Seq(
      scalapb.gen() -> (sourceManaged in Compile).value
    )
  )
  .disablePlugins(AssemblyPlugin)

lazy val common = project
  .settings(
    name := "Common",
    settings,
    libraryDependencies ++= commonDependencies,
    scalaSource in Compile := file("Common/src")
  )
  .disablePlugins(AssemblyPlugin)
  .dependsOn(protos)

lazy val ingress = project
  .settings(
    name := "Ingress",
    settings,
    assemblySettings,
    libraryDependencies ++= Seq(dependencies.databricks),
    scalaSource in Compile := file("Ingress/src")
  )
  .dependsOn(
    common
  )

**Comment by thesamet** [comment]
I think that you're doing everything right. Don't rely on IntelliJ showing things in red to know if there are any errors. Please test with `sbt compile`, IntelliJ sometimes need to have the project re-imported when certain type of changes happen to the project.

What error are you seeing when you are trying `sbt compile`?

**Comment by sidtandon2014** [comment]
Thanks Nadav. After making some changes in build.sbt its working now.
I am closing this issue
