### ISSUE TITLE
Generating code from 'external' proto files

### ISSUE THREAD

**Issue by raboof** [thesamet/sbt-protoc#144]
Currently, when introducing a dependency with the `"protobuf"` configuration, its proto files get added to `externalIncludePath`.

This works great when the artifact also contains correctly-generated classes, like is the case when getting com.google.protobuf resources from `scalapb-runtime`.

On the other hand, it does not work when the artifacts contains the generated files in a different style than desired (or when it contains no generated files at all), for example when trying to use  `com.google.api.grpc:grpc-google-cloud-pubsub-v1` with ScalaPB.

In that situation, so far I've worked around this by just adding the external include path to the `protoSources` wholesale (`PB.protoSources += PB.externalIncludePath.value)`) - but that is of course rather unsophisticated.

What would you think about providing another way to introduce .proto files from external artifacts into the `protoSources`? Perhaps a `"protobuf-src"` configuration that fetches the .proto files from an artifact without introducing its classpath?

**Comment by thesamet** [comment]
The proposed change makes sense. Will you be able to provide a PR?

Related to this, I've been thinking of publishing common third-party protos (such as the one you referred to) already in precompiled form for a matrix of versions of Scala and ScalaPB.

**Comment by raboof** [comment]
> Will you be able to provide a PR?

I'll give it a try, probably somewhere this or next week

**Comment by thesamet** [comment]
I added support for `protobuf-src` and an example of the main README.md.

I also created a new repo which will be used to publish pre-compile ScalaPB libraries: https://github.com/scalapb/common-protos

List of what we have so far: https://repo1.maven.org/maven2/com/thesamet/scalapb/common-protos/

**Comment by raboof** [comment]
This looks great!
