### ISSUE TITLE
Generate protobuf classes from external jar

### ISSUE THREAD

**Issue by nattyddubbs** [thesamet/sbt-protoc#15]
I have the need to use messages from a third party jar that contains *.proto definitions for their interface.

I do not need to write any *.proto messages myself but only need to generate Scala classes from their jar that contains the message definitions.

How can I do this using sbt-protoc? I attempted to do 

`PB.protoSources in Compile := Seq((target)(_ / "protobuf-external").value)`

As well as add the jar to my library dependencies but that does not work.

Is this a capability of sbt-protoc? I can see the *.proto files in the /target/protobuf_external directory but can't seem to generate them.

Thank you for the help

**Comment by thesamet** [comment]
I was unable to reproduce this problem. I added the line you included above in one of my example projects and the external protos were generated and compiled. Can you publish a minimal example?

**Comment by nattyddubbs** [comment]
Will do. I'll update the thread when I have it.

**Comment by thesamet** [comment]
I've just noticed that in your code snippet you wrote `protobuf-external` though it should be `protobuf_external` (with an underscore) - which could explain why it does not generate code for the dependencies.

I added a question to the FAQ about generating code for external JARS: https://scalapb.github.io/faq.html

Here is an example where it is used in a multi-project build:
https://github.com/thesamet/sbt-protoc/tree/master/examples/multi-with-external-jar
