### ISSUE TITLE
Deploy sbt-protoc to Bintray rather than repo1?

### ISSUE THREAD

**Issue by mindloaf** [thesamet/sbt-protoc#17]
For users that use Artifactory to cache repo1, the sbt-protoc fails to cache properly (and is thus not usable) due to:

https://www.jfrog.com/jira/browse/RTFACT-6235

sbt-protobuf doesn't have the same issue since it is distributed from [Bintray](https://bintray.com/sbt/sbt-plugin-releases/sbt-protobuf). Moving to Bintray as well as getting sbt-protoc added to [sbt](https://github.com/sbt) per [Plugins Best Practices](http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html) would help achieve your stated goal of superseding sbt-protobuf.

**Comment by thesamet** [comment]
Submitted a request to link to this package from the SBT community packages on bintray.

**Comment by thesamet** [comment]
Done, sbt-protoc 0.99.7 is served through bintray.
