### ISSUE TITLE
How to set custom OutputStream to protoc-jar

### ISSUE THREAD

**Issue by xuwei-k** [thesamet/sbt-protoc#172]
I want to set `OutputStream out` and `OutputStream err` parameters (default value is `System.out` and `System.err`)

https://github.com/os72/protoc-jar/blob/69c72f2bd4351d099dd2c8c051164153db7f914f/src/main/java/com/github/os72/protocjar/Protoc.java#L54-L58

```scala
PB.runProtoc := { args =>
  com.github.os72.protocjar.Protoc.runProtoc(
    PB.protocVersion.value +: args.toArray,
    streams.value.binary(),
    streams.value.binary()
  )
}
```

- https://github.com/sbt/sbt/blob/v1.3.13/main/src/main/scala/sbt/Keys.scala#L477
- https://github.com/sbt/sbt/blob/v1.3.13/tasks-standard/src/main/scala/sbt/std/Streams.scala#L61-L62

but got error 😢 

```
A setting cannot depend on a task
[error]  streams.value.binary(),
[error]  ^
[error] one error found
```

Should we change to

```diff
-      val runProtoc = SettingKey[Seq[String] => Int](
+      val runProtoc = SettingKey[(Seq[String], TaskStreams) => Int]( // break compatibility 😢 
```

https://github.com/thesamet/sbt-protoc/blob/ac4bfd830618e2dc79f2d5a791991d259ad03990/src/main/scala/sbtprotoc/ProtocPlugin.scala#L50

or something 🤔

**Comment by thesamet** [comment]
Hi @xuwei-k , @bjaglin  looked into this in the past and found out 
at https://github.com/os72/protoc-jar/issues/74 that protoc is hard-ced to log some stuff into stdout](https://github.com/os72/protoc-jar/blob/69c72f2bd4351d099dd2c8c051164153db7f914f/src/main/java/com/github/os72/protocjar/Protoc.java#L437-L439).
Perhaps it's worth revisiting PR #121 - I wonder if there are alternatives to the custom logger there that looks for line breaks. Can you take a look?

**Comment by bjaglin** [comment]
Thanks for the plug @thesamet. I have still hopes to resume work on it one day - [there was not much left for trying to capture only the logs from protoc itself](https://github.com/thesamet/sbt-protoc/pull/121#discussion_r344897106) - the tricky part was the debug output from protoc-jar, but any help is of course appreciated!

**Comment by thesamet** [comment]
I have some news on this issue. In sbt-protoc 1.0.0-RC1, I removed the dependency on protoc-jar, which is now directly downloaded from maven through an SBT dependency. Then `runProtoc` simply starts the process and connects `streams.value.log` to it, so it should be straightforward to customize.

See: https://github.com/thesamet/sbt-protoc/blob/20b2a2a75a4c336511a16c6b5f58423ef1d3bcc2/src/main/scala/sbtprotoc/ProtocPlugin.scala#L286-L292
And 1.0.0-RC1 CHANGELOG: https://github.com/thesamet/sbt-protoc/blob/master/CHANGELOG.md#100-rc1

I believe the issue can be closed, and I am looking forward for your feedback.
