### ISSUE TITLE
PB.protocVersion scope

### ISSUE THREAD

**Issue by thesamet** [thesamet/sbt-protoc#175]
In 1.0.0-RC1 possibly PB.protocVersion is looked up globally and not under the Compile. This needs to be verified, see https://github.com/scalapb/ScalaPB/commit/ddd992a6a14b08d75381f5226c905beadf8717ef#diff-fdc3abdfd754eeb24090dbd90aeec2ceL286

**Comment by bjaglin** [comment]
Isn't that expected? It sounds reasonable to me that all configs of the same project uses the same protocVersion. That's also why I didn't scope by config in the doc I added in https://github.com/thesamet/sbt-protoc/commit/f6070ef1f7ccf0a88fdd23de32c1eedcf3208f30#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115

**Comment by thesamet** [comment]
I noticed it when working on ScalaPB's own build.sbt, since it used `PB.protocVersion in Compile`, so I wanted to avoid a regression that impacts others. However, it looks like it was never documentation to work within a scope - so no need to preserve the previous behavior.
