### ISSUE TITLE
Better cache invalidation for custom, local generators

### ISSUE THREAD

**Issue by bjaglin** [thesamet/sbt-protoc#208]
Follows https://github.com/thesamet/sbt-protoc/pull/162

How can we accurately fingerprint `protoc-bridge` **local** (defined in the meta-build) generators behind `PB.targets`, to avoid false positive cache hits on local workspaces ~as ScalaPB/sbt-akka-grpc gets bumped for example~?

Looking up a potential `serialVersionUID` on `Generator` would allow generators to declare their version, but it leaves that responsibility to the generator author to bump this... ~I can't think of any other way - maybe something related to JAR timestamps?~

**Comment by thesamet** [comment]
I wasn't able to reproduce this with ScalaPB and akka-grpc. Can you provide a test setup?

On a test project, when I do `show protocArguments` (which is used to detect changes) I can see the generator versions:
```
sbt:zff> show protocArguments
[info] prj / Compile / protocArguments
[info] 	Arguments(List(/tmp/zff/prj/src/main/protobuf, /tmp/zff/prj/target/protobuf_external_src, /tmp/zff/prj/src/main/proto, /tmp/zff/prj/target/protobuf_external),List(),true,List((scala,List(com.thesamet.scalapb:scalapb-runtime:0.10.7(crossVersion=true)),/tmp/zff/prj/target/scala-2.12/akka-grpc/main,List(flat_package)), (akka-grpc-scaladsl-trait,List(com.lightbend.akka.grpc:akka-grpc-runtime_2.12:1.0.1(crossVersion=false)),/tmp/zff/prj/target/scala-2.12/akka-grpc/main,List(flat_package)), (akka-grpc-scaladsl-client,List(io.grpc:grpc-stub:1.30.2(crossVersion=false), com.lightbend.akka.grpc:akka-grpc-runtime_2.12:1.0.1(crossVersion=false)),/tmp/zff/prj/target/scala-2.12/akka-grpc/main,List(flat_package)), (akka-grpc-scaladsl-server,List(com.lightbend.akka.grpc:akka-grpc-runtime_2.12:1.0.1(crossVersion=false)),/tmp/zff/prj/target/scala-2.12/akka-grpc/main,List(flat_package))))
```

There should also be a local file that is used for comparison for cache invalidation:
```
cat prj/target/streams/compile/_global/_global/protocArguments/previous
["sbt.Task[sbtprotoc.ProtocPlugin$Arguments]",[["file:///tmp/zff/prj/src/main/protobuf/","file:///tmp/zff/prj/target/protobuf_external_src","file:///tmp/zff/prj/src/main/proto","file:///tmp/zff/prj/target/protobuf_external/"],[],true,[["scala",[["com.thesamet.scalapb","scalapb-runtime","0.10.7",true,null,{}]],"file:///tmp/zff/prj/target/scala-2.12/akka-grpc/main/",["flat_package"]],["akka-grpc-scaladsl-trait",[["com.lightbend.akka.grpc","akka-grpc-runtime_2.12","1.0.1",false,null,{}]],"file:///tmp/zff/prj/target/scala-2.12/akka-grpc/main/",["flat_package"]],["akka-grpc-scaladsl-client",[["io.grpc","grpc-stub","1.30.2",false,null,{}],["com.lightbend.akka.grpc","akka-grpc-runtime_2.12","1.0.1",false,null,{}]],"file:///tmp/zff/prj/target/scala-2.12/akka-grpc/main/",["flat_package"]],["akka-grpc-scaladsl-server",[["com.lightbend.akka.grpc","akka-grpc-runtime_2.12","1.0.1",false,null,{}]],"file:///tmp/zff/prj/target/scala-2.12/akka-grpc/main/",["flat_package"]]]]]
```

**Comment by bjaglin** [comment]
Apologies for the noise and the confusion, indeed https://github.com/thesamet/sbt-protoc/pull/162 did fix cache invalidation for generators packaged in a JAR. The problem is only for local generators defined within the meta-build - I am updating the description.

**Comment by thesamet** [comment]
Can you try the following? Assume metaGenProject is the SBT project where the generator is defined. For each project that depends on that meta generator:

```
  Compile / PB.generate / fileInputs +=
        (metaGenProject / Compile / sourceDirectory).value.toGlob / "**"
/ "*.scala",
  Compile / PB.recompile := (Compile / PB.recompile).value || (Compile / PB.generate).inputFileChanges.hasChanges
```

This would make the decision to rely on SBT change detection for the sources in the metaGenProject source files. Similarly, the generator being used locally can be named dynamically based on the hash of its sources.

**Comment by bjaglin** [comment]
We are defining custom protoc-bridge and akka-grpc generators (depending on the level of abstraction) in the sbt meta-build at the moment, but I should be able to adapt your proposal indeed :+1: 

Which leads me to a somewhat-related question: would it make sense to add helpers (or a new sbt config?) to sbt-protoc so that custom generators that do not come from an artifact (but a peer sbt project) can be loaded into `PB.targets` through an evolution of `SandboxedJvmGenerator` that wouldn't be artifact-centric? It does not seem trivial/possible at the moment. There is a chance that by doing that, the custom invalidation code above wouldn't be needed. I'd be willing to try that out at some point if that helps us moving our generators outside the sbt meta-build.

**Comment by thesamet** [comment]
I recently wrote a guide that tries to consolidate the best practices and all magic involved in writing plugins: https://scalapb.github.io/docs/writing-plugins

It comes with an [sbt plugin](https://github.com/thesamet/sbt-protoc-gen-project), as well as a [g8 template](https://github.com/thesamet/sbt-protoc-gen-project) to get projects set up correctly.

Specifically, to run plugins to run from a local project, it provides [codeGenClassPath and genModule](https://github.com/scalapb/protoc-gen-template.g8/blob/master/src/main/g8/build.sbt#L40-L47). Currently it re-generates sources on any compile, but the improvement we identified above can go into 
[here](https://github.com/thesamet/sbt-protoc-gen-project/blob/master/src/main/scala/sbtprotocgenproject/LocalCodeGenPlugin.scala#L52).

**Comment by bjaglin** [comment]
Thanks a lot, I completely missed https://github.com/thesamet/sbt-protoc-gen-project! I will try it out, and follow-up with PRs there along the way. https://github.com/thesamet/sbt-protoc-gen-project/blob/07380334e839f5b9f7431a89950f15275d91d6e7/src/main/scala/sbtprotocgenproject/LocalCodeGenPlugin.scala#L18-L19 precisely addresses/hacks my concerns about `SandboxedJvmGenerator` being artifact/coordinates-centric.

**Comment by bjaglin** [comment]
I have successfully migrated the custom generators from the sbt meta-build to a regular project, and tested the invalidation through source files watching, and it works well! For now, I inlined what's in https://github.com/thesamet/sbt-protoc-gen-project/blob/master/src/main/scala/sbtprotocgenproject/LocalCodeGenPlugin.scala, since it only supports using custom generators in `Compile`. I am not sure how far/generic you would like this to be, as I assume this plugin was only meant for e2e testing, not for defining generators in a monorepo?

I do notice a significant performance regression due to the lack of classloader caching, particularly visible as we have many sbt modules running `protoc` with custom generators. I am wondering if the classloader cache couldn't be bound to a task execution, like https://github.com/scalacenter/sbt-scalafix/blob/c5bb9c363d1202cff1907a5e3c85e503ae52c0f2/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L163-L171? Instead of disabling it completely, the user could then chose between a cache bound to the sbt session or the task invocation? For now, I have re-enabled the cache, which means that we effectively still have stale generated files after generator changes, but at least after a sbt reload, they get re-generated.


```diff
-generators in meta-build
 generators in regular project without cacheloader cache
+generators in regular project with cacheloader cache
```

`$ time sbt protocGenerate`

#### sbt cold, project cold (after `git clean -fdx`) = CI

```diff
-[success] Total time: 34 s, completed Jan 13, 2021, 9:49:12 AM
-real	1m23.087s
-user	3m50.854s
-sys	0m6.159s
 [success] Total time: 55 s, completed Jan 13, 2021, 9:30:32 AM
 real	1m39.524s
 user	5m1.112s
 sys	0m7.666s
+[success] Total time: 36 s, completed Jan 13, 2021, 10:13:16 AM
+real	1m23.052s
+user	3m58.006s
+sys	0m6.552s

```

#### sbt warm, project cold (after `sbt clean`)

```diff
-[success] Total time: 34 s, completed Jan 13, 2021, 9:51:14 AM
-real	0m57.722s
-user	2m46.017s
-sys	0m5.376s
 [success] Total time: 51 s, completed Jan 13, 2021, 9:25:58 AM
 real	1m14.935s
 user	3m45.212s
 sys	0m7.105s
+[success] Total time: 36 s, completed Jan 13, 2021, 10:15:34 AM
+real	1m1.070s
+user	2m51.165s
+sys	0m5.295s
```

#### sbt warm, project warm (after `sbt protocGenerate`)

```diff
-[success] Total time: 5 s, completed Jan 13, 2021, 9:53:05 AM
-real	0m28.050s
-user	1m22.907s
-sys	0m2.838s
 [success] Total time: 6 s, completed Jan 13, 2021, 9:27:54 AM
 real	0m30.190s
 user	1m26.488s
 sys	0m2.614s
+[success] Total time: 5 s, completed Jan 13, 2021, 10:17:23 AM
+real	0m28.485s
+user	1m25.771s
+sys	0m2.412s
```

**Comment by thesamet** [comment]
> I am not sure how far/generic you would like this to be, as I assume this plugin was only meant for e2e testing, not for defining generators in a monorepo?

Thanks for trying this! Right, when writing this plugin I had in mind projects like ScalaPB/zio-grpc/scalapb-validate which are meant to produce a protoc plugin and have one or two e2e projects to verify it. Will gladly accept PRs that improve performance and how classloader caching is done.
