### ISSUE TITLE
include_std_types no longer supported

### ISSUE THREAD

**Issue by raboof** [thesamet/sbt-protoc#210]
protoc-jar introduces a `--include_std_types` option, which when enabled extracts the proto's shipped with protoc and adds them to the include path (https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L64 and below).

It looks like basically the same can be achieved by adding `"com.thesamet.scalapb.common-protos" %% "proto-google-common-protos-scalapb_0.10"` to the protobuf sbt configuration.

I guess we should not re-introduce `--include_std_types`, but instead document using the `google-common-protos`? Perhaps link to that configuration in the error message when we encounter that option?

**Comment by thesamet** [comment]
Hi @raboof , actually, you need to add `protobuf-java` not `proto-google-common-protos`, or `scalapb-runtime` if using ScalaPB. I added a more prominent note about it in [this commit](https://github.com/thesamet/sbt-protoc/commit/178d619f04064ad7bebd77ed81801f67c98ec464).
This is already covered in multiple places throughout the docs:
* [README of sbt-protoc](https://github.com/thesamet/sbt-protoc/blob/6f19b538578950627f7b74bcf80cf28ec61bb929/README.md#additional-options) under "Make protos from some jar available to import".
* https://scalapb.github.io/docs/installation#installing-in-sbt-recommended
* https://scalapb.github.io/docs/sbt-settings#basic-installation
* https://scalapb.github.io/docs/faq#i-am-getting-import-was-not-found-or-had-errors

Will be happy to take PRs that can further eliminate confusion.
