### ISSUE TITLE
Windows 10: Could not find or load main class protocbridge.frontend.BridgeApp

### ISSUE THREAD

**Issue by thesamet** [thesamet/sbt-protoc#215]
See [Stackoverflow issue](https://stackoverflow.com/questions/65848016/how-to-solve-problem-with-compile-protobuf-in-scala-project-on-windows10?noredirect=1#comment116457573_65848016)

User reporting the following error for a vanilla build on Windows 10. Tried JVM 8 and 11:

```
[info] Compiling schema C:\Users\<.....>\IdeaProjects\LearnScala\custom-grpc\proto-example\src\main\protobuf\hello.proto
Error: Could not find or load main class protocbridge.frontend.BridgeApp
--jvm_0_out: protoc-gen-jvm_0: Plugin failed with status code 1.
```

**Comment by thesamet** [comment]
Next step for debugging:

1. Add the following to `project/plugins.sbt` (only needed when sbt-protoc <= 1.0.0, later versions of sbt-protoc will bring this version of protoc-bridge transitively):
    ```
    libraryDependencies += "com.thesamet.scalapb" %% "protoc-bridge" % "0.9.1"
    ```

2. Start sbt with the following command line options:
    ```
    sbt --debug  -Dprotocbridge.debug=1
    ```

    Ignore all the debug logs when sbt starts.

3. Type `compile` in the sbt prompt.

4. Look for a line like this:
    ```
    [debug] Executing protoc with [--plugin=protoc-gen-jvm_1=SCRIPT, ...]
    ```
    The SCRIPT above stands for some absolute path to a shell script on your system (should have a `bat` extension on Windows).

5. The `protocbridge.debug` above makes protocbrdige not delete the script when it's done, so you should be able to look it up, and even run it manually in a terminal.

* Can you paste the content of that script here?
* Is it pointing to the `java.exe` you expect it to? It should be the same one used by sbt itself.
* The script attempts to start java.exe and provide it a classpath that will help it find `protocbridge.frontend.BridgeApp` in the `-cp` argument. Can you find the class file with that name under the directory?
* What changes should be made to make this script work in your system?

**Comment by uuushka** [comment]
@thesamet I'm sorry, I have path with cyrillic  characters to .sbt directory with global plugins but project in path not contains cyrillic characters. 
you can close the task, thanks
