### ISSUE TITLE
How to import proto file from subproject

### ISSUE THREAD

**Issue by IntelligyScience** [thesamet/sbt-protoc#22]
Hi,
I have subprojects with SBT.

```
lazy val protoSetting = Seq(
  PB.targets in Compile := Seq(
    scalapb.gen() ->  (sourceManaged in Compile).value//(scalaSource in Compile).value / "buffer"
  )
)

lazy val sharedBase = (project in file("sharedBase")).settings(
  scalaVersion := scalaV,
  credentials += Credentials(Path.userHome / ".sbt" / "isCredentials"),
  resolvers ++= standardResolver,
  libraryDependencies ++= standardDeps,
  protoSetting
)

lazy val purchaseDepartment = (project in file("purchaseDepartment")).settings(
  scalaVersion := scalaV,
  credentials += Credentials(Path.userHome / ".sbt" / "isCredentials"),
  resolvers ++= standardResolver,
  libraryDependencies ++= standardDeps,
  protoSetting,
  PB.protoSources in Compile += target.value / "protobuf_external" / "de" / "scalamat" / "event" / "common"
).enablePlugins(DockerPlugin).dependsOn(sharedBase)
```

Now I have a proto file laying inside the sharedBase. How I can add now this proto to my proto in the purchasedepartment?

Thank you

**Comment by thesamet** [comment]
To make sure protoc is searching for files in sharedBase when it encounters an "import" statement in a proto file, add something like this to purchaseDepartment's settings:

`PB.includePaths in Compile += file("../sharedBase/src/main/protobuf")

**Comment by IntelligyScience** [comment]
ok. and which important statement should i use in proto?

**Comment by thesamet** [comment]
if the protos are directly under `sharedBase/src/main/protobuf`, then import `filename.proto` would work. I suggest though putting the proto files one directory down, like `sharedBase/src/main/protobuf/mypkg/` and importing them like this: `import "pkg/filename.proto"`.

**Comment by IntelligyScience** [comment]
ok. Thanks. That was the problem. Only to know, after importing I have to address the type compete? like  packagename.messageType ?

**Comment by thesamet** [comment]
Yes, if there's a package statement in file A, and file B imports file A, and file file (B) has a different package statement (or no package statement) then you need to reference types by the package name.
