### ISSUE TITLE
publish to maven central instead of bintray

### ISSUE THREAD

**Issue by xuwei-k** [thesamet/sbt-protoc#236]
- https://github.com/sbt/sbt/issues/6294
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

**Comment by CEikermann** [comment]
jfyi: every sbt build is broken today because of Bintray brown-out session https://status.bintray.com/

**Comment by thesamet** [comment]
thanks for reporting! I wasn't aware of the brownout - will get a version on maven asap.

**Comment by thesamet** [comment]
1.0.3 is on its way to maven.

**Comment by CEikermann** [comment]
Awesome thanks for the fast support!!
