### ISSUE TITLE
missing scalapb/scalapb.proto when compiling in sbt multi-project

### ISSUE THREAD

**Issue by ykoehler** [thesamet/sbt-protoc#241]
I have a multi-project sbt file, where my sub-project has protobuf files, those gets detected and converted to java, but an error occurs as the scalapb/scalapb.proto is not found.  Works great when in root projects.  Somehow the target/<project>/protobuf_external doesn't get updated properly when using sbt subproject.

**Comment by thesamet** [comment]
Hi @ykoehler , you need to have:
```
libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"
```

In the `settings` of the sub-project that references `scalapb/scalapb.proto`. See example: https://github.com/thesamet/sbt-protoc/blob/master/examples/scalajs-multiproject/build.sbt

If the issue still persists, please provide a minimal example for how to reproduce this issue.

**Comment by ykoehler** [comment]
ok, I was able to solve it doing that, but I am curious why having this libraryDependencies globally didn't work and got re-apply to the sub-project...

**Comment by thesamet** [comment]
> ok, I was able to solve it doing that, but I am curious why having this libraryDependencies globally didn't work and got re-apply to the sub-project...

@ykoehler That's just how SBT works, the value of `libraryDependencies` is overridden in sub-projects and not inherited. That's true for all dependencies, not just those in the `protobuf` scope.
