### ISSUE TITLE
Allow disabling `ScalaPB-Options-Proto`

### ISSUE THREAD

**Issue by plaflamme** [thesamet/sbt-protoc#249]
The automatic addition of files to the compile scope has consequences on non-scalapb plugins that might be configured in targets. This may break compilation due to files that were never requested to be included which makes this rather confusing fro the end-user (the only way to discover this is to extract the arguments passed to the `protoc` compiler).

It would be important to allow disabling this behaviour through an `sbt` option. e.g.:

```sbt
.settings(
  PB.includeScalaPbOptionsProtoFiles := false
)
```

Or perhaps expose the files themselves as a key and let the user override it:

```sbt
.settings(
  PB.scalaPbOptionsProtoFiles := Nil // override the list of unpacked files with an empty list
)
```

Alternatively, instead of including the files directly in the compile scope, `sbt-protoc` could offer the ability to generate a custom file that only have import statements to those options files. e.g.:

```protobuf
import "scalapb/validate-options.proto"
import "validate/scalapb-options.proto"
```

This could even be entirely templated so that `sbt-protoc` has no opinions at all about how to include those files in the compile pipeline of a project. e.g.:

```sbt
PB.scalaPbOptionsProtoTemplate := """package my.custom.package;
{{scalapbOptionsProtoImports}}
"""
```

Ideally, the generated path + filename would also be configurable.

For context: we use a linting plugin on our `proto` files and it started complaining about the package names (it has rules for the package names) in some files in our compile scope (e.g.: `scalapb` and `validate`). This wasn't the case before since those packages were in the import path and the linting plugin doesn't cover those (obviously).

**Comment by thesamet** [comment]
Thanks for reporting. Can this issue be addressed by configuring the linter, like excluding these files? Which linter are you using? What's the actual lint error? Generally, third-party files should be excluded from linting since they are not bound to the rest of the project's standards.

**Comment by plaflamme** [comment]
1. yes, we can disable the rules on a per directory or file basis
2. we use the [lint plugin](https://docs.buf.build/lint-overview) from https://buf.build/
3. the error is that the package names do not follow the versioning rule defined [here](https://docs.buf.build/lint-rules#package_version_suffix)
4. yes, third-party files can be excluded, but it's annoying to have to exclude files that we didn't ask for in the first place

The problem that this causes for us is that we now have to manually go and update our linting rules in tens of projects for files that we didn't include in our build in the first place; which is pretty confusing.

FWIW: the fact that this declaration:

```sbt
libraryDependencies ++= Seq(
  "my.group" %% "some-proto-dependency-to-import" % "1.0" % "protobuf",
  "my.group" %% "some-proto-dependency-to-import" % "1.0",
)
```
affects the `protobuf-src` scope is a problem IMO.

**Comment by thesamet** [comment]
I am not sure we have an alternative at this point. Disabling the automated addition of the option files is going to generate code that may not compile. Wouldn't it be sufficient/simpler to let the linter exclude everything under `target`?

**Comment by plaflamme** [comment]
We can certainly edit our linter configuration, but as I mentioned, it's pretty surprising that we have to do that considering that we never included these files in the compiler's scope. It's pretty confusing that we have to exclude files from the linter's "compile" scope that were only declared in the "import" scope.

I understand what these options are trying to solve, but perhaps we can find a less "opinionated" way to solve this?

A few options I can think of:
* add an opt-out sbt setting and let the user deal with the consequences
  * by not overriding scalapb options;
  * by importing those files manually, e.g.: `import scalapb/validate-options.proto` in their own files;
* provide the templating mechanism described earlier
  * in our case, this allows generating the file in such a way that it would pass our linting rules

Again, whatever our problem is, I believe that this new feature will cause confusion since additions to the "import" scope like this one now affect the "compile" scope:

```sbt
libraryDependencies +=
  // this makes the files available for import, but now may also affect the "protobuf-src" scope without any indication
  "com.thesamet.scalapb" %% "scalapb-validate-core" % scalapb.validate.compiler.BuildInfo.version % "protobuf"

```

**Comment by thesamet** [comment]
I agree with you that the side-effect of having sources add is surprising. I am fine with adding an opt-out option. The documentation should be clear on the consequences along the lines of "users are expected to manually import the option files through one of their source files to avoid possible compile errors due to inconsistent settings".

**Comment by plaflamme** [comment]
I can give it a try, sure... any opinion on the `sbt` setting's name?

**Comment by thesamet** [comment]
How about`PB.disableManifestProcessing := true` to opt-out? The main change will go in here: https://github.com/thesamet/sbt-protoc/blob/master/src/main/scala/sbtprotoc/ProtocPlugin.scala#L553-L555

**Comment by plaflamme** [comment]
@thesamet here's [the PR](https://github.com/thesamet/sbt-protoc/pull/250)
