### ISSUE TITLE
grpc?

### ISSUE THREAD

**Issue by schmitch** [thesamet/sbt-protoc#26]
Hello, since I only wanted to use java protobuf with sbt, this plugin seems, perfectly for me.
However as far as I seen, this does not support grpc, is that correct?

it would be great to have grpc support.

**Comment by thesamet** [comment]
It is possible, but there's some boilerplate. I've added this example: https://github.com/thesamet/sbt-protoc/tree/master/examples/grpc-java

**Comment by schmitch** [comment]
wow thanks @thesamet I didn't know that there was `IO.download`. wouldn't it make sense to download protoc the same way you did it in that example code, instead of relying on a third party dependendcy, which repackes `protoc`?
I would help, but my `sbt` knowledge is rather poor.
