### ISSUE TITLE
proto files from external directories not picked up

### ISSUE THREAD

**Issue by rabejens** [thesamet/sbt-protoc#277]
My `.proto` files lie in a directory outside of my SBT project because I also use them in other projects in the same repository.

I have this in my `build.sbt`:

```
lazy val common =
  project
    .settings {
      libraryDependencies += "com.google.protobuf" % "protobuf-java" % "3.19.1" % "protobuf"
      Compile / PB.targets := Seq(PB.gens.java -> (Compile / sourceManaged).value)
      Compile / PB.protoSources := Seq(sourceDirectory.value.getParentFile.getParentFile.getParentFile / "protos")
    }
```

However, when I run `compile`, I get:

`[info] Protobufs files found, but PB.targets is empty.`

When I swap the two `PB` settings around, the message goes away but no code is generated and compiled. When copying the proto files into `src/main/protobuf`, it works.

What am I missing, or is this a bug?

**Comment by thesamet** [comment]
Hi @rabejens , the return value of a code block in Scala (`{ ... }`) is the last expression in it. So

```
val x = {
  1
  2
  3
}
```

is the same as `val x = 3`

For the specific code snippet you provided, the `settings` function only gets the last setting you give it, and this is why changing the order makes a difference. The correct way to do it would be to use `()` and pass each setting as an argument:

```
.settings(
  setting1,
  setting2,
  setting3
)
```

I am curious if you found the curly-brackets syntax somewhere in the ScalaPB docs or elsewhere? If so, let me know where so I can fix it.

**Comment by rabejens** [comment]
Hello,

I am really banging my head on my keyboard for this, but yes, I used the wrong parentheses/brackets/whatever.

With round brackets, it works.
