### ISSUE TITLE
Can't download 0.99.29+ for sbt 0.13

### ISSUE THREAD

**Issue by mbrito-yieldstreet** [thesamet/sbt-protoc#301]
I'm trying to use a `sbt-protoc` version with support for `protobuf-src` configuration in an sbt 0.13 project, but apparently, artifacts for 0.99.28 and later weren't published.

**Comment by thesamet** [comment]
Hi @mbrito-yieldstreet , the plugin artifacts are available here: https://scala.jfrog.io/ui/native/sbt-plugin-releases/com.thesamet/sbt-protoc/scala_2.12/sbt_1.0/

Up to a certain point in time, the plugins were published to bintray, howevery bintray was sunset. See this: https://www.scala-sbt.org/1.x/docs/Bintray-For-Plugins.html

Perhaps your version of sbt isn't configured correctly to pull in from the new location. If you can't update sbt to a newer version, see if you can customize the resolvers in `project/plugins.sbt`.
