### ISSUE TITLE
protoc downloaded twice

### ISSUE THREAD

**Issue by brandon-leapyear** [thesamet/sbt-protoc#304]
In `build.sbt`, we have `protocVersion` hardcoded to the version of protoc we want to use, but then when building, we notice two versions of `protoc` getting downloaded:
```console
$ PROTOC_CACHE=$PWD/foo sbt
sbt:leapyear-spark-compute> core/compile
[info] Updating 
https://artifacts.leapyear.io/artifactory/leapyear-jar-all/com/google/protobuf/protoc/3.13.0/protoc-3.13.0.pom
  100.0% [##########] 5.0 KiB (11.2 KiB / s)
[info] Resolved  dependencies
[info] Updating 
https://artifacts.leapyear.io/artifactory/leapyear-jar-all/com/google/protobuf/protoc/3.20.0/protoc-3.20.0.pom
  100.0% [##########] 5.5 KiB (9.0 KiB / s)
[info] Resolved  dependencies
```
(using `PROTOC_CACHE` to force the redownload; we also have our own mirror for serving artifacts)

I believe this is a bug; `sbt-protoc` should only be downloading the version of `protoc` that it'll use

**Comment by thesamet** [comment]
I was able to reproduce in a build with multiple subprojects, where a subproject overrides `PB.protocVersion`. It looks like the root project has the original `PB.protocVersion` value and the plugin attempts to download protoc for it too. The fix would involve preventing sbt-protoc from downloading protoc for subprojects (or the root project) if they don't have proto files. It's unclear why it's not already the case and requires some investigation.

As a temporary workaround, you can define PB.protocVersion for the root project with the same version. Then the second lookup would be a cache hit.

**Comment by bjaglin** [comment]
I assume it's because https://github.com/thesamet/sbt-protoc/blob/d16c1b07153cf188e165a5e9f60f9c8f19835470/src/main/scala/sbtprotoc/ProtocPlugin.scala#L334 brings false negatives: it should also check for absence of proto files. Will confirm and send a PR.
