### ISSUE TITLE
Plugin dependency resolution error on sbt 1.5+

### ISSUE THREAD

**Issue by dkichler** [thesamet/sbt-protoc#314]
I have encountered an issue where the `protoc-gen-validate` plugin is unable to resolve.  

The issue appears to only manifest in a fairly specific scenario:
- In the context of a module that depends on another module through `dependsOn`, including the `protobuf` scope.
- On sbt 1.5+

I have prepared this project to demonstrate the scenario and corresponding failed resolution (please note the tag):  
https://github.com/dkichler/protoc-plugin-resolution-issue/tree/reproduce-protoc-resolution-broken

Reproduced on macOS 12.5

**Comment by thesamet** [comment]
Thanks for reporting and providing this minimal repo. What is the intent of `protobuf->protobuf` dependency? Is there anything that doesn't work as intended when you remove it?

**Comment by dkichler** [comment]
Hmm, taking a closer look revealed my misunderstanding.  I had the impression that `protobuf->protobuf` was necessary to bring proto sources from downstream module into scope of the dependent module.  It appears that is not the case and a standard dependsOn brings all protos into scope, as demonstrated in the [dependsOn test](https://github.com/thesamet/sbt-protoc/blob/master/src/sbt-test/settings/depends-on/build.sbt).

The `protobuf->protobuf` did have the affect of inheriting `protobuf` scoped library dependencies transitively from the downstream module (as you would expect).  However, this shouldn't be necessary since the module should bring in any necessary dependencies explicitly rather than transitively (as per the common settings in the test).

Removing `protobuf->protobuf` does alleviate the problem, and it's effect can be replicated with more explicit/proper config.

Considering the above, I think this can be closed.  Appreciate the time to look at it.
