### ISSUE TITLE
optional fields not supported

### ISSUE THREAD

**Issue by marvelfrozen** [thesamet/sbt-protoc#315]
included protoc jar cannot generate code with optional keywords.
then i tried changing the protoc version to latest, and got below error instead
are there any plans to update the library to support optional keywords?

> promo.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-jvm_0 hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--jvm_0_out: 
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:416)
[error]         at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:514)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$11(ProtocPlugin.scala:521)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:394)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error]         at sbt.util.Difference.apply(Tracked.scala:414)
[error]         at sbt.util.Difference.apply(Tracked.scala:389)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error]         at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:526)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:832)
[error] (Compile / protocGenerate) protoc returned exit code: 1

**Comment by thesamet** [comment]
Hi @marvelfrozen, the error implies that one of the code generators in your build doesn't support proto3 optionals. Which ones are you using?

**Comment by marvelfrozen** [comment]
we're using sbt-protoc 1.0.0-RC2 and scalapb compilerplugin 0.10.8
upgrading it to 1.0.3 and 0.11.11 respectively turns up another error of `Duplicate mappings` where files with same name conflicting each other even though they are not in same folder

anyway, i will close this issue since apparently our team didn't really need that `optional` keyword, so we solve the issue by removing it from the proto file.

thank you.
