### ISSUE TITLE
How to generate protos from another sbt-plugin project?

### ISSUE THREAD

**Issue by bjhartin** [thesamet/sbt-protoc#317]
Hello,

I'm working on an sbt plugin which _itself_ needs to generate classes from proto files.  Do you support a simple programmatic use case?  I'd like to encapsulate the scalapb/protoc to hide this from my users, who are primarily concerned with generating a number of different files from a swagger contract.  To them, the interface is (logically) `SwaggerContract => Output(Seq[ScalaFile], Seq[ProtoFile], ...)`

Thanks!

**Comment by thesamet** [comment]
Hi @bjhartin , I think the easiest way to do what you described would be to have your plugin modify `PB.targets` for the projects it's applied on, and then sbt-protoc would do the rest. If that's not what you're looking for, maybe elaborate more on your use case?

**Comment by bjhartin** [comment]
Hi @thesamet, sorry for the late reply.

I resolved this by using `addSbtPlugin("com.thesamet" % "sbt-protoc" % Dependencies.sbtProtocV)` in the _build.sbt_ of my plugin project.  This allows me to reference the protoc tasks and append them to the operations I am providing.

My use case is code generation from a swagger/asyncApi contracts.  I am generating three things from a contract:

- *.proto files
- *.scala files from ScalaPB (which are _never_ to be seen by the developers, due to issue of weak typing, optionality, etc.)
- *.scala _model_ files which represent the contract and provide much tighter typing than is possible with proto classes.  Typeclasses/syntax exist so one can say 

- `val order: Try[Order] = fromProtoBytes[Order]`
- `val bytes = order.toProtoBytes`

The intent is to discourage or prevent developers from using *.proto files as contracts and scalaPB classes as models, which has led to much confusion.

**Comment by thesamet** [comment]
Thanks for sharing the context. Protos leaking into application business logic and beyond ser/deser is something every fairly large project eventually needs to deal with. 

It sounds like you are able to accomplish what you intended. Is it ok to close the issue?

**Comment by bjhartin** [comment]
Yes, thanks
