### ISSUE TITLE
Unresolved dependencies for 0.99.10

### ISSUE THREAD

**Issue by qux42** [thesamet/sbt-protoc#34]
Hello,

addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.10")

throws an Error:
unresolved dependency: com.thesamet#sbt-protoc;0.99.10: not found

the same with all other versions

**Comment by qux42** [comment]
I think it's because I'm using scala 2.12. For scala 2.11 it's working...

**Comment by thesamet** [comment]
If you are using sbt 0.13.x, then the Scala version of the plugin would be 2.10, but you can use it with any version of Scala - so working with 2.12 shouldn't be a problem. You need to check which URLs it is attempting to download sbt-protoc from. The official location is here https://dl.bintray.com/sbt/sbt-plugin-releases/com.thesamet/sbt-protoc/scala_2.10/sbt_0.13/0.99.11/jars/

**Comment by qux42** [comment]
Thanks, it's working when you don't have the scala version set in ~/.sbt/0.13/global.sbt on 2.12
