### ISSUE TITLE
No jar is generated

### ISSUE THREAD

**Issue by dudo** [thesamet/sbt-protoc#358]
I'm running `sbt assembly`, but it fails with `java.nio.file.NoSuchFileException`. There is indeed no jar file generated. The code compiles, and the `target/scala-2.13/classes` and `target/scala-2.13/src_managed` directories are full of the files that I'd expect to see.

I'm running it with a simple 

```scala
Compile / PB.protoSources := Seq(baseDirectory.value / ".." / "proto")

Compile / PB.targets := Seq(
  scalapb.gen() -> (Compile / sourceManaged).value
)
```

Did I miss something?

**Comment by thesamet** [comment]
Hi @dudo , please provide a minimal project that demonstrates the problem you are describing as well as a full stack trace. If the class files are generated, what indicates that the issue is related to sbt-protoc?

**Comment by dudo** [comment]
I guess I'm more wondering... should this generate a jar file from the generated pb files ootb?

**Comment by thesamet** [comment]
I'd expect `sbt assembly` to pick up the generated class files. This shouldn't require any additional sbt configuration or cause a failure.

**Comment by dudo** [comment]
🤦 I had a slash in the name. I'm so sorry to bother you. Once you said it should work, I commented out as much as I could from `build.sbt`, and it did, indeed, build. 

Thank you!

**Comment by dudo** [comment]
For posterity, this was the first Java project that I was hosting on GitHub packages. I mistakenly thought the name had to be `org/repo`.
