### ISSUE TITLE
Exclude dependencies in protobuf configuration from generated POMs

### ISSUE THREAD

**Issue by alexleigh** [thesamet/sbt-protoc#41]
I followed the example to add external Jars containing .proto files needed for compilation, by adding a snippet like the following:

```
libraryDependencies ++= Seq(
  "com.google.protobuf" % "protobuf-java" % "3.4.0" % "protobuf"
)
```

The compilation works. However, when publishing the project to Ivy, library dependencies added to the protobuf configuration are listed as compile dependencies in the generated POM file. I only needed these external Jars to compile the proto files, they are not needed as dependencies of the generated Jar. Is there a way to exclude these external dependencies from the generated POM file when packaging and publishing?

**Comment by thesamet** [comment]
As a workaround you can add this to your build.sbt:

```
    pomPostProcess := { (node: scala.xml.Node) =>
      new scala.xml.transform.RuleTransformer(new scala.xml.transform.RewriteRule {
        override def transform(node: scala.xml.Node): scala.xml.NodeSeq = node match {
          case e: scala.xml.Elem if e.label == "dependency" && e.child.exists(child => child.label == "artifactId" && child.text.startsWith("protobuf-java")) =>
            scala.xml.Comment(s"protobuf-java has been removed.")
          case _ => node
        }
      }).transform(node).head
    }
```

I think that this is a bug in SBT, rather than in ScalaPB.

**Comment by alexleigh** [comment]
Thank you, that worked.
