### ISSUE TITLE
proto files in test scope in a multi-module project are not picked up

### ISSUE THREAD

**Issue by reikje** [thesamet/sbt-protoc#43]
I have a multi-module project and one module is called `core`. I am trying to generate code for the proto file inside `core/src/test/protobuf` but the file is never picked up in test scope (i.e. running `test:compile`. I have added this to `build.sbt` running sbt 0.13.16.

    lazy val core = Project("core", file("core"))
      .settings(
        ... // other stuff
        PB.targets in Compile := Seq(scalapb.gen(grpc=false) -> (sourceManaged in Compile).value),
        PB.targets in Test := Seq(scalapb.gen(grpc=false) -> (sourceManaged in Test).value)
     )

**Comment by thesamet** [comment]
By default sbt-protoc sets some keys only on the compile configuration. For getting it to work with the test configuration, you need to add some settings. It should look something like this:

```
lazy val core = Project("core", file("core"))
  .settings(
    ... // other stuff
    PB.targets in Compile := Seq(scalapb.gen(grpc=false) -> (sourceManaged in Compile).value),
    PB.targets in Test := Seq(scalapb.gen(grpc=false) -> (sourceManaged in Test).value),
    inConfig(Test)(sbtprotoc.ProtocPlugin.protobufConfigSettings)
 )
```

**Comment by reikje** [comment]
Worked like I charm, thanks. Added a note in the README
