### ISSUE TITLE
Doesn't work with other `sourceGenerators in Compile`

### ISSUE THREAD

**Issue by analytically** [thesamet/sbt-protoc#6]
When other sourceGenerators are specified, protoc seems to delete the target directory, deleting any other generated sources.

**Comment by thesamet** [comment]
Yes. Fix on the way and will be released soon. In the mean time, you can set the target directory to be a subdirectory of sourceManaged.

**Comment by analytically** [comment]
Thanks!

**Comment by analytically** [comment]
Would you be able to point me to the bug in the source code? I can perhaps submit a PR.

**Comment by thesamet** [comment]
The deletion happens here - https://github.com/thesamet/sbt-protoc/blob/master/src/main/scala/sbtprotoc/ProtocPlugin.scala#L99  

I have some code that fixes it by generating code into a temp directory and then moves them to the target directory. This is needed so the plugin can reliably report which files it created (vs other source generators). It's almost ready, just needs a little ironing. Stay tuned.

**Comment by thesamet** [comment]
In 0.99.3, you can add to your build.sbt a line like:

```
PB.deleteTargetDirecory := true
```

Which would prevent the deletion from happening. The downside, is that you'll manually have to clean up if you end up with unnecessary generated code there. This can happen if you create a.proto, generate, then remove a.proto and generate. The generated code for a.proto would remain until you clean.

**Comment by analytically** [comment]
Still doesn't seem to work for me. I'll investigate more.

**Comment by thesamet** [comment]
Correction, it should have been:

```
PB.deleteTargetDirecory := false
```

(true is the default)

**Comment by analytically** [comment]
I have the following in my build:

```
sourceGenerators in Compile += generateVersion(sourceManaged in Compile, _ / "Version.scala",
 """|package sbux.ucp.svc
    |
    |import java.time.Instant
    |
    |case object Version {
    |  val current: String = "%s"
    |  val sbtVersion: String = "%s"
    |  val builtAt: Instant = Instant.ofEpochMilli(%sL)
    |}
    |""").taskValue,
```

And with sbt-protoc this file gets deleted, all the time.

**Comment by thesamet** [comment]
There are a few other complications with shared directory for generated files. My best recommendation for now is to generate into a subdirectory:

```
PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value / "protobuf"
)
```

**Comment by Citrullin** [comment]
@thesamet There's a typo in your code ;)
Correct version:
```
PB.deleteTargetDirectory := false
```
