### ISSUE TITLE
How should I run all proto file?

### ISSUE THREAD

**Issue by thinkerou** [thesamet/sbt-protoc#66]
I know that add one proto file from https://github.com/thesamet/scalapb-maven-example/blob/master/pom.xml#L109
but I want to run all proto at src/test/ directory, like src/test/*.proto, how should I do? thanks!

**Comment by thesamet** [comment]
@jet-black - you had a similar issue on scalapb/ScalaPB#445 - can you share how you solved it? (I wasn't able to use my own proposal of using fileset)

**Comment by jet-black** [comment]
Here is full example (with java support):
https://github.com/jet-black/extended-maven-scalapb
Ask me, if you have any questions.

**Comment by thinkerou** [comment]
@jet-black thanks a lot! I will test tonight.

**Comment by thesamet** [comment]
Closing for now. We are using github for tracking bugs. Please use gitter, mailing list, or stackoverflow for usage questions.
