### ISSUE TITLE
Scala optional type is not supported?

### ISSUE THREAD

**Issue by cwei-bgl** [thesamet/sbt-protoc#68]
Hi,

Thanks for the great plugin. It looks Scala optional type is not supported? It is not a stopper. Just it will be more convenient if it is supported.

Thanks, Cheng

**Comment by thesamet** [comment]
Hi Cheng, If you are using proto3 syntax, look into [primitive wrappers](https://scalapb.github.io/customizations.html). If you use proto2 syntax, the generator generates `Option` types by default for optional fields.

If you have any further questions, please use the ScalaPB mailing list. Github issues are meant for tracking issues.
