### ISSUE TITLE
Wrong protoc for Unix system

### ISSUE THREAD

**Issue by AlexanderShniperson** [thesamet/sbt-protoc#69]
Hi

I'm trying to compile `proto` files with required version `v261` and looks like `protoc-jar` takes wrong version, here is messages
```
protoc-jar: protoc version: 2.6.1, detected platform: osx-x86_64 (mac os x/x86_64)
protoc-jar: embedded: bin/2.6.1/protoc-2.6.1-osx-x86_64.exe
```
As you can see i have Mac osx and protoc takes `exe` Windows executable version, but it should be binary executable Unix based protoc

**Comment by AlexanderShniperson** [comment]
oh i see that i created issue at wrong repo, alreadey opened it at [related project](https://github.com/os72/protoc-jar/issues/46)

**Comment by thesamet** [comment]
Looks like you are getting a `osx-x86_64` executable (the exe extensions is confusing). AFAIK, protoc-jar doesn't include a freebsd binary for protoc. Your best option would be to install one on your system, and point ScalaPB at it (there's documentation on how to do that).

**Comment by AlexanderShniperson** [comment]
@thesamet yes you are right, it's works and confusing

**Comment by os72** [comment]
protoc-jar does support BSD for 2.6.1 (3rd party contribution). It's not embedded but should download automatically
