### ISSUE TITLE
Compiling to Proto3, need Proto2

### ISSUE THREAD

**Issue by pauljamescleary** [thesamet/sbt-protoc#75]
I have a proto file for proto 2.6.1.  It must compile to proto 2.6.

However, when I do a compile, it looks like the generated Java is for proto3 ...

I find this in the generated java
```
com.google.protobuf.GeneratedMessageV3 
```

I am getting lots of compiler failures, because `GeneratedMessageV3` is not found (which makes sense since I am using proto-java 2.6.1.

In my sbt, I have this...

```
  PB.targets in Compile := Seq(
    PB.gens.java("2.6.1") -> (sourceManaged in Compile).value
  )
```

In the proto file, I have...

```
syntax = "proto2";
```

Is there something I am doing incorrectly?

**Comment by pauljamescleary** [comment]
Here is the compile error...

```
/src_managed/main/vinyldns/proto/VinylDNSProto.java:15828:7: not found: type com
[error]       com.google.protobuf.GeneratedMessageV3 implements
```

**Comment by thesamet** [comment]
Hey Paul, the version you specify in `PB.gens.java("2.6.1")` affects the version of the `protobuf-java` library that gets added to your library dependencies. To control the version of protoc you are using, add:

```
PB.protocVersion := "-v261"
```

**Comment by pauljamescleary** [comment]
Just to confirm, with this plugin I do _not_ have to have protoc installed is that correct?  Sorry for the question in comments.

This definitely worked.

**Comment by thesamet** [comment]
Correct, this plugin depends on https://github.com/os72/protoc-jar which ships with many different versions of protoc. Currently 3.5.1 is the default version. Also, you can set `PB.runProtoc` if you want `sbt-protoc` to use a locally installed protoc instead.

**Comment by pauljamescleary** [comment]
Thanks!  Looks like this works!

FYI, this is the PR I just posted for our repo - https://github.com/vinyldns/vinyldns/pull/113
