### ISSUE TITLE
FreeBSD protoc has a static dependency on /usr/local/lib/gcc49/libstdc++.so.6: version CXXABI_1.3.9

### ISSUE THREAD

**Issue by GuyIncognito1986** [thesamet/sbt-protoc#77]
We should build and package protoc with all dependencies really, it's trivial to fix on the box, but might be annoying for new users.

**Comment by GuyIncognito1986** [comment]
15:59:36 protoc-jar: saved: /tmp/protocjar.webcache/com/github/os72/protoc/3.5.1-build2/protoc-3.5.1-build2-freebsd-x86_64.exe
15:59:36 protoc-jar: executing: [/tmp/protocjar4718248550231015808/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge6147639593495891713, --scala_out=flat_package,grpc:/usr/local/jenkins/workspace/Direct Trader Akka/target/scala-2.12/src_managed/main, -I/usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf, -I/usr/local/jenkins/workspace/Direct Trader Akka/target/protobuf_external, -I/usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf, -I/usr/local/jenkins/workspace/Direct Trader Akka/target/protobuf_external, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/ingramStaticData.proto, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/analyticsService.proto, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/spireStaticData.proto, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/config.proto, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/opencart.proto, /usr/local/jenkins/workspace/Direct Trader Akka/src/main/protobuf/categoryImport.proto]
15:59:36 /usr/local/lib/gcc49/libstdc++.so.6: version CXXABI_1.3.9 required by /tmp/protocjar4718248550231015808/bin/protoc.exe not found

**Comment by thesamet** [comment]
Closing as this responsibility is delegated to protoc-jar.
