### ISSUE TITLE
Use scalapb-protoc with Dotty

### ISSUE THREAD

**Issue by lodo1995** [thesamet/sbt-protoc#81]
I'm trying to set up a project with Dotty.

Currently my `project/protoc.sbt` looks like this:

    addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.19")

    libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.8.3"

I'm using libraries compiled to Scala 2.12 by using `withDottyCompat` in my `build.sbt`, as explained in [the Dotty docs](https://github.com/lampepfl/dotty-example-project#getting-your-project-to-compile-with-dotty):

    lazy val root = project
        .in(file("."))
        .settings(
            libraryDependencies ++= scalaDeps.map(_.withDottyCompat(scalaVersion.value))
                                 ++ javaDeps
        )

Unfortunately, it appears that `sbt-protoc` is adding runtime dependencies using `%%`, which makes it pick up the Dotty version (currently `0.13`):

    [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency:
                     com.thesamet.scalapb#scalapb-runtime_0.13;0.8.3: not found

**Comment by thesamet** [comment]
Until this gets resolved you should be able to manually remove the dependency and add the correct one:

```
libraryDependencies -= "com.thesamet.scalapb" %% "scalapb-runtime" % "0.8.3"
libraryDependencies += ("com.thesamet.scalapb" %% "scalapb-runtime" % "0.8.3").withDottyCompat(scalaVersion.value)
```

**Comment by lodo1995** [comment]
@thesamet thank you.
Adding those two lines fixed the problem.

**Comment by erwan** [comment]
I've been unable to apply the workaround (it's still trying to pick a Dotty artifact), is there a sample project somewhere with dotty and sbt-protoc?

**Comment by thesamet** [comment]
I put together a project that demonstrates the workaround here: https://github.com/thesamet/scalapb-dotty-example

**Comment by erwan** [comment]
thank you!

**Comment by thesamet** [comment]
Sure thing. Note that current snapshot versions of ScalaPB support Dotty 0.27, so the workaround is not necessary in that case, see for example https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/scalapb-runtime_0.27/

**Comment by PhilAndrew** [comment]
I tried and IntelliJ Scala plugin didn't like the generated source files

**Comment by thesamet** [comment]
Hi @PhilAndrew , are you on the latest versions of sbt-protoc and ScalaPB? Can you clarify what it means for IntelliJ not to like the generated source files? Does it work in SBT but not in IntelliJ? If so, it would be considered a bug on the IntelliJ side.

**Comment by PhilAndrew** [comment]
Hi @thesamet I created some issues.

https://github.com/scalapb/ScalaPB/issues/985
https://youtrack.jetbrains.com/issue/SCL-18477

I'll try to upgrade things and see.

**Comment by thesamet** [comment]
I believe this issue can be closed. ScalaPB 0.11.x is tested and released with Scala 3. Usage is documented in https://scalapb.github.io/docs/dotty
